import "./global.css";
import Sidebar from "./component/sidebar";

import { personalData } from "../data/page-data";

export const metadata = {
  title: "Resume App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col sm:flex-row">
        <Sidebar data={personalData} />
        <main className="flex flex-col w-full p-10 ml-auto sm:w-2/3 sm:p-10">
          {children}
        </main>
      </body>
    </html>
  );
}
